/**
 * Skill taxonomy — kebab-case slugs grouped by job category.
 *
 * Used by the JD generator and the skill autocomplete on the job form.
 * Each entry is a stable, lowercase, kebab-case identifier (canonical form).
 *
 * Keep entries sorted alphabetically — search performance relies on stable
 * ordering for prefix-match dedup. Extend additively; do NOT remove entries
 * already used by published jobs.
 */

const RAW_SKILLS: readonly string[] = [
  // ---------------------------------------------------------------------------
  // Technology — backend, frontend, infra, data plumbing
  // ---------------------------------------------------------------------------
  'ansible',
  'apollo-graphql',
  'argo-cd',
  'astro',
  'aws',
  'aws-lambda',
  'azure',
  'bash',
  'bun',
  'c-sharp',
  'cassandra',
  'celery',
  'chef',
  'ci-cd',
  'circleci',
  'cloudflare',
  'cloudflare-workers',
  'cobol',
  'cpp',
  'css',
  'cypress',
  'datadog',
  'deno',
  'devops',
  'django',
  'docker',
  'dotnet',
  'elasticsearch',
  'electron',
  'elixir',
  'erlang',
  'expo',
  'express-js',
  'fastapi',
  'firebase',
  'flask',
  'flutter',
  'gcp',
  'gin',
  'git',
  'github-actions',
  'gitlab-ci',
  'go',
  'graphql',
  'grpc',
  'haskell',
  'helm',
  'html',
  'http',
  'jakarta-ee',
  'java',
  'javascript',
  'jenkins',
  'jest',
  'jquery',
  'kafka',
  'kibana',
  'kotlin',
  'kubernetes',
  'laravel',
  'linux',
  'mariadb',
  'memcached',
  'microservices',
  'mongodb',
  'mqtt',
  'mysql',
  'nestjs',
  'netty',
  'next-js',
  'nginx',
  'nodejs',
  'npm',
  'nuxt-js',
  'oauth2',
  'openapi',
  'pandas',
  'php',
  'playwright',
  'pnpm',
  'postgres',
  'prisma',
  'puppeteer',
  'python',
  'pytorch',
  'rabbitmq',
  'react',
  'react-native',
  'react-query',
  'redis',
  'redux',
  'rest-api',
  'ruby',
  'ruby-on-rails',
  'rust',
  'scala',
  'sentry',
  'shell-scripting',
  'sinatra',
  'socket-io',
  'solidity',
  'spring-boot',
  'sqlite',
  'storybook',
  'svelte',
  'swagger',
  'swift',
  'tailwind-css',
  'tdd',
  'tensorflow',
  'terraform',
  'testcafe',
  'three-js',
  'tomcat',
  'trpc',
  'typescript',
  'unit-testing',
  'vagrant',
  'vault',
  'vercel',
  'vite',
  'vitest',
  'vue-js',
  'webpack',
  'websocket',
  'yarn',
  'zustand',

  // ---------------------------------------------------------------------------
  // Design — visual, product, research
  // ---------------------------------------------------------------------------
  'accessibility',
  'adobe-xd',
  'after-effects',
  'animation',
  'brand-identity',
  'design-systems',
  'figma',
  'framer',
  'icon-design',
  'illustrator',
  'indesign',
  'interaction-design',
  'lottie',
  'motion-graphics',
  'photoshop',
  'prototyping',
  'sketch',
  'typography',
  'ui-design',
  'usability-testing',
  'ux-research',
  'ux-writing',
  'visual-design',
  'wireframing',
  'zeplin',

  // ---------------------------------------------------------------------------
  // Marketing — growth, content, paid, brand
  // ---------------------------------------------------------------------------
  'a-b-testing',
  'affiliate-marketing',
  'brand-strategy',
  'content-marketing',
  'content-strategy',
  'copywriting',
  'email-marketing',
  'facebook-ads',
  'google-ads',
  'google-analytics',
  'growth-hacking',
  'influencer-marketing',
  'instagram-marketing',
  'linkedin-ads',
  'marketing-automation',
  'pr',
  'public-relations',
  'sem',
  'seo',
  'social-media',
  'tiktok-marketing',
  'video-marketing',

  // ---------------------------------------------------------------------------
  // Data & Analytics
  // ---------------------------------------------------------------------------
  'airflow',
  'amplitude',
  'bigquery',
  'data-engineering',
  'data-modeling',
  'data-science',
  'data-visualization',
  'data-warehousing',
  'dbt',
  'etl',
  'looker',
  'machine-learning',
  'metabase',
  'mixpanel',
  'mlops',
  'numpy',
  'powerbi',
  'pyspark',
  'r-language',
  'scikit-learn',
  'snowflake',
  'spark',
  'sql',
  'statistical-analysis',
  'superset',
  'tableau',

  // ---------------------------------------------------------------------------
  // Sales / Customer Success
  // ---------------------------------------------------------------------------
  'account-management',
  'b2b-sales',
  'cold-calling',
  'crm',
  'customer-onboarding',
  'customer-success',
  'customer-support',
  'enterprise-sales',
  'forecasting',
  'hubspot',
  'inside-sales',
  'lead-generation',
  'negotiation',
  'pipedrive',
  'pipeline-management',
  'salesforce',
  'solution-selling',
  'territory-planning',
  'upselling',
  'zendesk',

  // ---------------------------------------------------------------------------
  // Operations / Project Management
  // ---------------------------------------------------------------------------
  'agile',
  'asana',
  'budgeting',
  'business-analysis',
  'change-management',
  'clickup',
  'confluence',
  'jira',
  'kanban',
  'kpi-tracking',
  'lean',
  'linear',
  'monday-com',
  'notion',
  'okrs',
  'pmp',
  'process-improvement',
  'product-management',
  'program-management',
  'project-management',
  'risk-management',
  'roadmapping',
  'scrum',
  'six-sigma',
  'stakeholder-management',
  'trello',
  'vendor-management',
  'waterfall',

  // ---------------------------------------------------------------------------
  // Finance / Legal / HR — back-office competencies
  // ---------------------------------------------------------------------------
  'accounting',
  'compliance',
  'contract-management',
  'financial-modeling',
  'gdpr',
  'payroll',
  'people-operations',
  'recruiting',
  'sourcing',
  'talent-acquisition',

  // ---------------------------------------------------------------------------
  // Soft skills
  // ---------------------------------------------------------------------------
  'adaptability',
  'analytical-thinking',
  'communication',
  'conflict-resolution',
  'creativity',
  'critical-thinking',
  'cross-functional-collaboration',
  'decision-making',
  'emotional-intelligence',
  'leadership',
  'mentoring',
  'organization',
  'presentation-skills',
  'problem-solving',
  'public-speaking',
  'teamwork',
  'time-management',
]

/** Canonical, sorted list of skill slugs. */
export const SKILLS: readonly string[] = Object.freeze(
  Array.from(new Set(RAW_SKILLS)).sort(),
)
