/**
 * Re-exports of Prisma model types + composite shapes used across the app.
 */

import type { Prisma } from "@prisma/client";

// -----------------------------------------------------------------------------
// Re-export everything generated by Prisma.
// -----------------------------------------------------------------------------
export type { Prisma } from "@prisma/client";
export {
  // enums
  UserStatus,
  GlobalRole,
  TenantRole,
  TenantStatus,
  PlanTier,
  JobStatus,
  EmploymentType,
  ExperienceLevel,
  LocationType,
  ApplicationStatus,
  CourseLevel,
  CourseStatus,
  LessonContentType,
  EnrollmentStatus,
  NotificationType,
  AuditAction,
} from "@prisma/client";

export type {
  Tenant,
  Branding,
  User,
  Account,
  Session,
  VerificationToken,
  UserTenant,
  TeamMember,
  Invitation,
  JobCategory,
  Job,
  Application,
  SavedJob,
  Resume,
  Course,
  Module,
  Lesson,
  Enrollment,
  LessonProgress,
  Certificate,
  Notification,
  AuditLog,
  Subscription,
} from "@prisma/client";

// -----------------------------------------------------------------------------
// Composite shapes (Prisma "validator" pattern for type-safe includes)
// -----------------------------------------------------------------------------

export const tenantWithBranding = {
  include: { branding: true },
} satisfies Prisma.TenantDefaultArgs;
export type TenantWithBranding = Prisma.TenantGetPayload<typeof tenantWithBranding>;

export const jobWithCategory = {
  include: {
    category: true,
    postedBy: { select: { id: true, name: true, image: true } },
    tenant: { select: { id: true, slug: true, name: true } },
  },
} satisfies Prisma.JobDefaultArgs;
export type JobWithCategory = Prisma.JobGetPayload<typeof jobWithCategory>;

export const applicationWithJob = {
  include: {
    job: { include: { category: true } },
    user: { select: { id: true, name: true, email: true, image: true } },
  },
} satisfies Prisma.ApplicationDefaultArgs;
export type ApplicationWithJob = Prisma.ApplicationGetPayload<typeof applicationWithJob>;

export const courseWithModules = {
  include: {
    modules: {
      orderBy: { order: "asc" },
      include: {
        lessons: { orderBy: { order: "asc" } },
      },
    },
    instructor: { select: { id: true, name: true, image: true } },
  },
} satisfies Prisma.CourseDefaultArgs;
export type CourseWithModules = Prisma.CourseGetPayload<typeof courseWithModules>;

export const userPublic = {
  select: {
    id: true,
    name: true,
    image: true,
    headline: true,
    location: true,
  },
} satisfies Prisma.UserDefaultArgs;
export type UserPublic = Prisma.UserGetPayload<typeof userPublic>;

export const userWithTenants = {
  include: {
    tenants: { include: { tenant: true } },
  },
} satisfies Prisma.UserDefaultArgs;
export type UserWithTenants = Prisma.UserGetPayload<typeof userWithTenants>;

export const enrollmentWithCourse = {
  include: {
    course: { include: { modules: { include: { lessons: true } } } },
    lessonProgress: true,
  },
} satisfies Prisma.EnrollmentDefaultArgs;
export type EnrollmentWithCourse = Prisma.EnrollmentGetPayload<typeof enrollmentWithCourse>;
